### ISSUE TITLE
Refonte du tri de l'API

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/jobs-caen-camp#56]
Tout comme le problème de pagination décrit dans [l'issue #55](https://github.com/CaenCamp/jobs-caen-camp/issues/55), une mise à jour récente de React-Admin a fait apparaitre un problème au niveau de l'implémentation actuelle du tri des listes de l'API.

Pour rappel, voici comment est déclarée la pagination de la contrat OpenAPI :

```yaml
// https://github.com/CaenCamp/jobs-caen-camp/blob/master/apps/api/openapi/openapi.yaml#L1060

    Sort:
      name: sort
      in: query
      description: "Le tri applicable à la liste. C'est un tableau stringifié de la forme [sortProp, sortDirection]"
      required: false
      explode: false
      schema:
        type: array
        maxItems: 2
        minItems: 2
        items:
          type: string
```

Même cause, même effet, le problème vient donc de l'utilisation d'un tableau *stringifié* pour gérer le tri. (Encore une fois, la lecture de l'issue [#55](https://github.com/CaenCamp/jobs-caen-camp/issues/55) vous renseignera sur le principe du problème à adresser dans cette issue).

Revenons à quelques *Best Practices* :

- [Best Practices for Designing a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#advanced-queries)
- [REST API Design: Filtering, Sorting, and Pagination](https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#sorting)

Je propose donc comme dans le cas de la pagination d'extraire les deux paramètres de tri utilisés dans la tableau `sort` en deux paramètres : `sortBy` et `orderBy`

Ce qui transformerait une ancienne requête `/api/organizations?sort=%5B%22title%22%2C%22DESC%22%5D` en `api/organizations?sortBy=title&orderBy=DESC`

On pourrait débattre du `camelCase` utilisé sur le nom de ces paramètres. Une url n'est pas sensible à la casse. En effet, le [W3C dit](https://www.w3.org/TR/WD-html40-970708/htmlweb.html):

> There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

Du coup, pourquoi ne pas utiliser du `kebab-case` ou du `snake_case` ?

Et bien parce que tout les paramètres d'un objet implémenté dans notre API sont en `camelCase` ! Entre autre pour être compatible avec schema.org. Du coup, nous devrons transmettre les filtres par propriété (voir l'issue #XX) en `camelCase`. Il semble donc préférable de rester cohérent.

**Par contre, il faudra bien considérer lors du traitement de ces paramètres de requête au niveau de l'API qu'ils ne doivent pas être sensibles à la casse !**

## Todo list

- [ ] Rédiger un `ADR` concernant cette nouvelle implémentation (pour l'historique. Ne pas hésiter à reprendre la présente issue)
- [ ] Reprendre la gestion du tri dans les `router`.s de `job-posting` et `organization`
- [ ] Reprendre la gestion du tri dans les `repository` de `job-posting` et `organization`
- [ ] Mettre à jour le contrat OpenAPI
- [ ] Mettre à jour les tests
- [ ] Mettre à jour le `dataProvider` de react-admin

Bref, c'est une très bonne occasion de rentrer dans le code du projet !

**Comment by Keksoj** [comment]
Albert et moi sommes dessus ! On a lu l'issue et on a déchiffré le code, on galère mais on est motiv' !

**Comment by AlbertLanne** [comment]
On a lu le code télécharger Stoplight est, on est en plein dessus !

**Comment by AlbertLanne** [comment]
Emmanuel et moi avons crée un dépo sur l'avancé de l'issues pour sortSanitizer, avec les test refactoré, n'hésitez pas à nous répondre avant que nous commettions des commits malheureux!
https://github.com/Keksoj/refactoring-school
