### ISSUE TITLE
Refonte des filtres de l'API

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/jobs-caen-camp#57]
Une mise à jour récente de React-Admin a fait apparaitre un problème au niveau de l'implémentation actuelle du tri ([issue #56](https://github.com/CaenCamp/jobs-caen-camp/issues/56)) et de la pagination ([issue #55](https://github.com/CaenCamp/jobs-caen-camp/issues/55)) des listes de l'API.

L'objet filtre utilisé actuellement n'est lui pas impacté par le problème de `JSON.stringify` du `sort` et du `pagination`. Pour autant, l'implémentation des filtres est-elle satisfaisante ?

Pour rappel, voici comment est déclarée la pagination dans la contrat OpenAPI :

```yaml
// https://github.com/CaenCamp/jobs-caen-camp/blob/master/apps/api/openapi/openapi.yaml#L1052

    Filter:
      name: filters
      in: query
      description: "Filtres appliquables à la requête. C'est un objet json stringifié, avec les filtres en clé/valeur séparé par des virgules."
      required: false
      explode: true
      schema:
        type: string
```

Nous avons donc un objet serialisé en json, portant les clé/valeur des filtres à appliquer. 
Une de problème évidant est la difficulté à documenter proprement cet objet filtre générique, en détaillant les clés applicable en fonction des objets filtrés.

Et regardons ce que disent les *Bests practices* concernant les filtres d'API :

- [Best Practices for Designing a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#advanced-queries)
- [REST API Design: Filtering, Sorting, and Pagination](https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#filtering)

Il semble donc qu'une première bonne pratique consiste tout d'abord à extraire chaque filtre en tant que paramètre de requête à part entière.

Ce qui transformerait une ancienne requête `/api/organizations?filters=%7B%22title%22%3A%22toto%22%2C%22postalCode%22%3A1400%7D` en `api/organizations?title=toto&postalCode=14000`

L'autre point / bonne pratique concerne la manière dont sera appliqué le filtre. En effet, pour le moment, nous avons de filtre qui ont des comportements différents et des nommages ne correspondant plus au nom de la propriété que l'on filtre. Par exemple, pour l'objet `jobPosting`, nous avons des filtres :

- `employmentType` qui filtre sur l'integralité de la valeur passée (en sql : `WHERE employment_type = 'value'`),
- `title` qui filtre sur un *LIKE* de la valeur passée (en sql : `WHERE title LIKE '%value'`),
- `jobStartDate_after` qui filtre sur une date de début d'emploi supérieure à la date passée en paramètre (en sql : `WHERE jobStartDate > dateValue`)

Et encore une fois, tout ceci est en l'état difficilement documentable via OpenAPI.

Pour répondre à ce probléme, je propose l'adoption des [RHS Colon](https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#rhs-colon) en les adaptant légèrement, c'est à dire : `key=value(:operator)`
L'opérateur devient alors optionnel, avec une valeur par défault `eq` (=). Ceci semble en effet plus facile à utiliser pour l'utilisateur final.

Voici une liste d'opérateur à implémenter :

| operateur | applicable à         | explication                 |
| --------- | -------------------- | --------------------------- |
| :eq       | string, number, date | Is equal to                 |
| :gt       | number, date         | Is greater than             |
| :lt       | number, date         | Is less than                |
| :gte      | number, date         | Is greater than or equal to |
| :lte      | number, date         | Is less than or equal to    |

Ce qui transformerait une ancienne requête `/api/organizations?filters={ employmentType: 'CDD', jobStartDate_after='2020/09/01' }` en `api/organizations?employmentType=CDD&jobStartDate=2020/09/01:gte`

Concernant les recherche de `%LIKE`, je propose de regrouper toutes ces requêtes sur un paramètre unique `q` qui effectura toujours une recherche de type `%LIKE` en base de données, quand bien même ce `LIKE` devrait être appliqué sur plusieurs champs en même temps.

Ce qui transformerait une ancienne requête `/api/organizations?filters={ title: 'Javasc' }` en `api/organizations?q=Javasc`

## Todo list

- [x] Rédiger un `ADR` concernant cette nouvelle implémentation (pour l'historique. Ne pas hésiter à reprendre la présente issue)
- [x] Reprendre la gestion du filtres dans les `router`.s de `job-posting` et `organization`
- [x] Reprendre la gestion du filtres dans les `repository` de `job-posting` et `organization`
- [x] Mettre à jour le contrat OpenAPI
- [x] Mettre à jour les tests
- [x] Mettre à jour le `dataProvider` de react-admin

Bref, c'est une très bonne occasion de rentrer dans le code du projet !

**Comment by Keksoj** [comment]
Je m'y attaque !

**Comment by Keksoj** [comment]
C'est en route.
Concernant les recherches de type `%LIKE%`, l'opérateur par défaut est maintenant documentable grâce au contrat OpenAPI (edit: c'est fait). On peut l'overrider par les autres options, également documentables.

Au point où j'en suis, implémenter le paramètre unique `q` est hors de ma portée. Je pense abandonner ce feature pour le moment, le laisser pour une future PR.

QUESTION : Vaut-il mieux fournir au front…
* UN paramètre `jobStartDate` qui prend deux opérateurs différents, `:lt` et `:gt`' ou bien
* DEUX paramètres, `jobStartDate_before` et `jobStartDate_after` ?

Après avoir implémenté la première solution, je suis en train de pencher pour la seconde.

**Comment by lalmat** [comment]
D'une manière générale, j'ai tendance à penser qu'il faut se poser la question de ce qui est le plus compréhensible pour celui qui reprendra ton code.
Je serait donc de ton avis, je préfère mois aussi la seconde option.

Attention sur les majuscules, j'aurais tendance à penser que c'est une source à ennui à cause de la casse... et que du coup, il peut s'en suivre un bug du fait du double schéma "CamelCase / SnakeCase". Que penses-tu de noms de variables comme "job_start_before" et "job_start_after" (ou jobdate_before, jobdate_after) ?

**Comment by Keksoj** [comment]
Merci pour ton avis.
Dans le code de l'api, le lowerCamelCase fait loi. `jobStartDate` est une propriété de l'objet requête, de la réponse, etc. Les paramètres actuels, `jobStartDate_before` et  `jobStartDate_after` ont un underscore pour mieux les parser, ce qui  <strike>devient inutile</strike> **reste utile** avec cette PR.

Voici comment un paramètre est défini par le contrat openAPI :

```yaml
DatePosted:   # UpperCamelCase (dans l'arborescence)
      name: datePosted  # lowerCamelCase (dans la requête)
      in: query
      description:   "Filtre: La date d'ajout de l'offre d'emploi, …"
```

Le snake_case est utilisé pour `postal_code` et `address_locality` cependant (pourquoi ?).

J'aime l'idée d'un `_before` et d'un `_after` qui s'accollent à des noms de variable qu'ils ne font que préciser. Leur utilité est de plus courte durée.
Ainsi on aurait `propriétéDeLObjet_précision`.

Je part sur le modèle à deux paramètres, avec cette casse - mais le débat reste ouvert.

**Comment by lalmat** [comment]
Ok, je dois l’admettre, je ne connais pas assez bien l’api pour en dire d’avantage, je laisse le soin aux profils plus expérimentés sur l’api de s’exprimer.

**Comment by alexisjanvier** [comment]
Hello,

Arfff vaste sujet ^^

Effectivement, la question tout d'abord de case est un peu pénible, et je ne suis pas certain qu'il y ait de bonne solution. Ce qui est important, c'est par contre d'adopter une stratégie cohérente et appliquée partout, parce que ce qui est horrible, c'est quand cela est fait de manière différentes sur le même projet. (pfff c'est le matin, je cherche mes mots).

Donc concernant la case, la règle pour le moment c'est utilisation du snake_case pour nommer les chose dans le PostgreSQL (nom des tables, des champs ...), mais utilisation du cameCase pour l'API. On a d'ailleur mis en place un système transformant automatiquement le camelCase en snake_case en entrée des requêtes SQL, et vis-versa en sortie !

Je ne dis pas que c'est la bonne solution, mais c'est une règle défini dans le guide du contributeur. Donc, si en cours de dev, tu vois du code qui ne respecte pas cette règle, n'hésites pas à la changer ! D'ailleur, je crois bien que ta PR en cours implique de remettre d'équerre pas mal de ces filtres en snake_case ^^ Et si la règle ne te convient pas, n'hésites pas à ouvrir une issue pour qu'on en discutte :) 

Concernant le `_before` et `_after`, en fait je dirais que c'est le même problème ! Le but de cette issue, en plus d'extraire chaque filtres dans un paramètre de requête distinct, c'est d'ajouter un `operator` à ces filtres. Pour pouvoir faire plus que du simple =. 

Cette issue et le début de ton implémentation prévoit de mettre en place un système cohérent d'operator, de type :

| operator | relevant for         | explanation                 |
| -------- | -------------------- | --------------------------- |
| :eq      | string, number, date | Is equal to                 |
| :gt      | number, date         | Is greater than             |
| :gte     | number, date         | Is greater than or equal to |
| :lt      | number, date         | Is less than                |
| :lte     | number, date         | Is less than or equal to    |
| :in      | string, number, date | Is in                       |
| :%l%     | string               | Is %LIKE%                   |
| :%l      | string               | Is %LIKE                    |
| :l%      | string               | Is LIKE%                    |

Cette solution est certainement contestable, je suis pas grand fan non plus. Mais c'est elle a l'avantage de répondre à la problématique et d'être partagé par une partie de la communauté de ceux qui galère à faire une API REST cohérente ... 

Utiliser un `_before` ou un `_after`, en vrai, c'est la même chose, mais en le nommant de manière différente. Et c'est bien aussi ! Mais par contre, ce dont je suis certain, c'est qu'il ne faut surtout pas mélanger les deux ! Il faut que tu fasses un choix cohérent ;)

**Comment by Keksoj** [comment]
Le système des opérateurs est super, je l'ai implémenté et ça rend le code plus clair :+1: 

La plupart des paramètres se voit attribuer un opérateur par défaut, qu'on peut overrider. Par exemple, `validThrough` a `:lt` par défaut, mais si requête précise `validThrough:lte` ça passe.

```js
const parametersThatDefaultToLT = [
    'validThrough',
    'datePosted_before',
    'jobStartDate_before',
];
// ...
    if (!filterOperator) {
    // ...
        if (parametersThatDefaultToLT.includes(filterKey)) {
                    filterOperator = FILTER_OPERATOR_LT;
                }
     // ...
    }
```
( [lien](https://github.com/Keksoj/jobs-caen-camp/blob/refactor-api-filters/apps/api/src/toolbox/sanitizers.js)

Mon problème: quel opérateur par défaut pour `jobStartDate` et `datePosted` ? Utiliser `eq` n'a pas vraiment de sens... Je me suis dit que ça valait le coup d'offrir au front la facilité de deux paramètres.

- `jobStartDate_before` parsé en `jobStartDate:lt`
- `jobStartDate_after` parsé en `jobStartDate:gt`

`lt` et `gt` sont attribués par défaut mais overridables aussi.
L'underscore est vraiment pratique pour parser !
C'est cela ou **imposer** au front d'utiliser les opérateurs, ce qui me va trés bien aussi, ça allège le code et résout ce problème de casse. Aidez-moi à décider !

> D'ailleur, je crois bien que ta PR en cours implique de remettre d'équerre pas mal de ces filtres en snake_case ^^

Damn j'ose pas j'ai peur de tout casser, il y a de la dentelle SQL que je ne maîtrise pas (>_<") :

```
 .select(
            'job_posting.*',
            'organization.name as hiringOrganizationName',
            'organization.postal_code as hiringOrganizationPostalCode',
            'organization.address_locality as hiringOrganizationAddressLocality',
            'organization.address_country as hiringOrganizationAddressCountry',
            'organization.image as hiringOrganizationImage',
            'organization.url as hiringOrganizationUrl'
        )
```


Mon code est prêt à être revu, d'ailleurs:
- [la branche concernée](https://github.com/Keksoj/jobs-caen-camp/tree/refactor-api-filters)
- [la Pull Request](https://github.com/CaenCamp/jobs-caen-camp/pull/69)
Je suis en train de rédiger l'ADR, mais il faut décider cette histoire de pamaètres `_before` vs. gestion côté front.

**Comment by alexisjanvier** [comment]
En fait, l'idée, c'est de **supprimer** tous les `jobStartDate_before` et autres `jobStartDate_after` qui n'ont plus de sens !

Pour un objet donné, on va definir sur quel champs on donne la possibilité de filtrer. 

Par exemple, en va dire que pour `jobPosting`, on peut filtrer par `title` et `jobStartDate`.     
Après, on décrit le vocabulaire des operateurs aux client de l'API (dans la doc OpenAPI). 
**Ce sera à eux d'utiliser judicieusement ce vocabulaire** ! Par exemple ils pourront faire un jobStartDate=2020-09-01 pour avoir les offre commençant au premier septembre (équivalant à jobStartDate:eq=2020-09-01 `:eq` étant l'operateur par default) ou JobStartDate:lt=2020-09-01 pour toutes les offres commencant avant le 1er septembre ! 

Mais encore une fois, le `jobStartDate_before` n'a plus de sens et doit ^etre supprimer. On autorise le filtre par `jobStartDate`, et on gère ensuite au mieux le fait qu'il pusiise être accompagné ou non d'un operateur `eq`, `gt`, `lte` ... 
 
Est-ce que cela te semble convenir ?

**Comment by Keksoj** [comment]
Impeccable tu réponds exactement à ma question, on part là-dessus ! Je supprime les `_béfore` et `_after`, ce sera au front d'apposer les bons opérateurs.

Par contre dans l'issue tu proposes ce format : `key=value(:operator)` avec comme exemple 

```api/organizations?employmentType=CDD&jobStartDate=2020/09/01:gte```

Et dans ton post juste ici tu utilises ```JobStartDate:lt=2020-09-01```

J'ai implémenté la première syntaxe dans la PR.

**Comment by alexisjanvier** [comment]
Il me semble que le manière la plus standard est ... la seconde :( Mais je te dirais ! A toir de faire ce qu'il te semble le plus facile ! 
L'argument en faveur de la première implementation, c'est l'operateur IN. Pour exemple, si on veut un serie d'object filtré par des id, on aura un id:in=[1, 2, 3], plus facile à priori à gérer côté back que id=[1,2,3]:in ....
Quoio que. A toi de décider ;)

**Comment by Keksoj** [comment]
Je vais voir la faisabilité et j'aviserai ;-)

**Comment by Keksoj** [comment]
C'est bon j'ai implémenté la syntaxe `filtre(:opérateur)=valeur`' rectifié la casse où il fallait, rédigé l'ADR, ça me semble bon pour la relecture!

**Comment by alexisjanvier** [comment]
Cool :+1: Je regarde ça attentivement ASAP (sans doute ce weekend)
